name: E2E avec MySQL + Apache + Cypress

on:
  push:
    branches: [ "test", "main" ]
  pull_request:
    branches: [ "test" , "main"]
  workflow_dispatch:

jobs:
  # Job environnement + test e2e cypress 
  e2e:
    runs-on: ubuntu-latest
    # Configuration des services
    services:
      # Service MySQL
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: taskdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpw"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    # Etapes du job
    steps:
      # Checkout du code(récupération depuis le repo github)
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup PHP, Composer, extensions
      - name: Setup PHP CLI (Composer & outils)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, sodium, zip
          tools: composer
          coverage: none
      
      # installation des dépendances composer
      - name: Installer dépendances Composer
        run: composer install --no-interaction --prefer-dist
      
      # migration de la base de données
      - name: Importer la base de données
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpw < base.sql
      
      # build env.php for test 
      - name: Build env.php for the app test
        run: |
          cat > env.php <<'PHP'
          <?php
          const BDD_LOGIN = "root";
          const BDD_PASSWORD = "rootpw";
          const BDD_SERVER = "127.0.0.1:3306";
          const BDD_NAME = "taskdb";
          const BASE_URL = "/";
          PHP
      
      # Démmarage du serveur PHP sur le port 8000
      - name: start PHP
        run: php -S 127.0.0.1:8000 &

      # Cypress Actions 
      - name : Test Cypress
        uses: cypress-io/github-action@v6
      
  # Job de deploiement par FTP
  deploy:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      # Checkout du code(récupération depuis le repo github)
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup PHP, Composer, extensions
      - name: Setup PHP CLI (Composer & outils)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, sodium, zip
          tools: composer
          coverage: none
      
      # installation des dépendances composer prod
      - name: Installer dépendances Composer
        run: composer install --no-interaction --prefer-dist
      
      # build env.php for prod
      - name: Build env.php for the app prod
        run: |
          cat > env.php <<'PHP'
          <?php
          const BDD_LOGIN = "${{ secrets.BDD_LOGIN }}";
          const BDD_PASSWORD = "${{ secrets.BDD_PASSWORD }}";
          const BDD_SERVER = "${{ secrets.BDD_HOST }}";
          const BDD_NAME = "${{ secrets.BDD_NAME }}";
          const BASE_URL = "/";
          PHP
      
      # Deployment via FTP
      - name: 📂 Deployment to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
